version: '3'
services:
  toro-api:
    restart: always
    depends_on:
      - db
    container_name: toro_backend
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    network_mode: "host"

  db:
    image: mysql

    command: --default-authentication-plugin=mysql_native_password
    restart: always

    volumes:
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: toro
      MYSQL_USER: toro
      MYSQL_PASSWORD: toro
      MYSQL_ROOT_PASSWORD: toro

    ports:
      - 3306:3306

  toro-web:
    restart: always
    depends_on:
      - toro-api
    container_name: toro-web
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    network_mode: "host"
