"""empty message

Revision ID: d5e8571cb2f8
Revises:
Create Date: 2023-07-13 18:18:54.503615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d5e8571cb2f8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("code"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("cpf", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cpf"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("branch", sa.String(length=5), server_default="0001", nullable=True),
        sa.Column(
            "amount",
            sa.DECIMAL(precision=10, scale=2),
            server_default="0",
            nullable=True,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.execute("ALTER TABLE accounts AUTO_INCREMENT = 300101;")
    op.create_table(
        "user_assets",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("assets_code", sa.String(length=10), nullable=True),
        sa.Column("quantity", sa.Integer(), server_default="0", nullable=True),
        sa.ForeignKeyConstraint(
            ["assets_code"],
            ["assets.code"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_assets")
    op.drop_table("accounts")
    op.drop_table("users")
    op.drop_table("assets")
    # ### end Alembic commands ###
